
services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq-broker
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - rede-lab

  api-produtora:
    build: ./api-produtora
    container_name: api-produtora
    ports:
      - "8080:8080"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - rede-lab

  worker-consumidor:
    build: ./worker-consumidor
    container_name: worker-consumidor
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - rede-lab

networks:
  rede-lab:
    driver: bridge
