version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management # A tag "management" inclui o painel visual
    container_name: rabbitmq-broker
    ports:
      - "5672:5672"   # Porta padrão para comunicação (onde o Spring Boot vai conectar)
      - "15672:15672" # Porta do painel visual (Interface Web)
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    networks:
      - lab-network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Garante que as filas não sumam se o contêiner reiniciar

networks:
  lab-network:
    driver: bridge # Quando formos para a OCI (Swarm), mudaremos para "overlay"

volumes:
  rabbitmq_data:
