name: Contar Commits na Branch

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  contar-commits:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do codigo com historico completo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Essencial para trazer o historico de commits

      - name: Contar e printar os commits
        run: |
          echo "A branch atual é: ${{ github.ref_name }}"
          
          # Conta quantos commits existem na branch atual
          NUM_COMMITS=$(git rev-list --count HEAD)
          
          echo "Total de commits nesta branch: $NUM_COMMITS"
