name: Info da Branch e Repositorio

on:
  push:
    branches:
      - 'feature/api-front-end'
  pull_request:
    branches:
      - 'feature/api-front-end'

jobs:
  info-branches:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do codigo com historico completo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Contar commits na branch atual
        run: |
          echo "A branch atual é: ${{ github.ref_name }}"
          NUM_COMMITS=$(git rev-list --count HEAD)
          echo "Total de commits nesta branch: $NUM_COMMITS"

      - name: Listar todas as branches do repositorio
        run: |
          echo "=== Listando todas as branches remotas ==="
          git branch -r
          
          echo -e "\n=== Listando todas as branches (locais e remotas) ==="
          git branch -a
